# Generated by Django 3.1.4 on 2025-11-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('eventos', '0002_auto_20251110_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='pessoas.pessoa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to='pessoas.pessoa'),
        ),
        migrations.AddField(
            model_name='local',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.endereco'),
        ),
    ]
