# Generated by Django 3.1.4 on 2025-11-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_pessoa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='participou',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
